name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: super-linter/super-linter@v7.3.0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.3.0
